# Generated by Django 4.0.3 on 2022-10-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_books_category_books_pages_alter_books_bookname'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='avatar',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[(1, 'Lãng mạn'), (2, 'Trinh thám'), (3, 'Khoa học'), (4, 'Nghệ Thuật'), (5, 'Thể Thao')], default='', max_length=1),
        ),
    ]
