# Generated by Django 4.0.3 on 2022-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_books_avatar_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Lãng mạn', 'Lãng mạn'), ('Trinh thám', 'Trinh thám'), ('Khoa học', 'Khoa học'), ('Nghệ Thuật', 'Nghệ Thuật'), ('Thể Thao', 'Thể Thao')], default='', max_length=12),
        ),
    ]
