# Generated by Django 4.0.3 on 2022-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_books_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_register',
        ),
        migrations.AlterField(
            model_name='books',
            name='bookName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Lãng mạn', 'Lãng mạn'), ('Trinh thám', 'Trinh thám'), ('Khoa học', 'Khoa học'), ('Nghệ Thuật', 'Nghệ Thuật'), ('Thể Thao', 'Thể Thao')], default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
