# Generated by Django 4.0.3 on 2022-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_books_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='releaseDate',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=4),
        ),
    ]
