# Generated by Django 4.0.3 on 2022-10-21 11:21

from enum import unique
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_books_releasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoiGian', models.CharField(default=None, max_length=200, unique=True)),
                ('nhietDo', models.CharField(default=None, max_length=200)),
                ('doAm', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
