# Generated by Django 4.0.3 on 2022-10-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_thoitiet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoitiet',
            name='thoiGian',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
