# Generated by Django 4.0.3 on 2022-11-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_thoitiet_thoigian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
