# Generated by Django 4.0.3 on 2022-11-12 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_alter_books_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nguoi_Dung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(max_length=100)),
                ('ten', models.CharField(max_length=100)),
                ('cardID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='books',
            name='releaseDate',
            field=models.IntegerField(default='2022', validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1)]),
        ),
    ]
