# Generated by Django 4.0.3 on 2022-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_nguoi_dung_alter_books_pages_alter_books_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoi_dung',
            name='cardID',
            field=models.CharField(max_length=8),
        ),
    ]
