# Generated by Django 4.0.3 on 2022-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_nguoi_dung_cardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoi_dung',
            name='thoigianVAO',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
