# Generated by Django 4.0.3 on 2022-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_nguoi_dung_thoiginra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoi_dung',
            name='thoigianVAO',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
