# Generated by Django 4.0.3 on 2022-11-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_alter_nguoi_dung_thoiginra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoi_dung',
            old_name='thoiginRA',
            new_name='thoigianRA',
        ),
    ]
