# Generated by Django 4.0.3 on 2022-11-12 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_rename_thoiginra_nguoi_dung_thoigianra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ida', models.IntegerField(default=0)),
                ('cardID', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 13, 2, 21, 48, 160128))),
                ('time_in', models.TimeField(default=datetime.datetime(2022, 11, 13, 2, 21, 48, 160128))),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('status', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='nguoi_dung',
            old_name='ho',
            new_name='hoten',
        ),
        migrations.RemoveField(
            model_name='nguoi_dung',
            name='ten',
        ),
    ]
