# Generated by Django 4.0.3 on 2022-11-12 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_log_rename_ho_nguoi_dung_hoten_remove_nguoi_dung_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 2, 24, 43, 62172)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2022, 11, 13, 2, 24, 43, 62172)),
        ),
    ]
