# Generated by Django 4.0.3 on 2022-11-12 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_alter_log_date_alter_log_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 2, 36, 1, 693002)),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2022, 11, 13, 2, 36, 1, 693002)),
        ),
        migrations.AlterField(
            model_name='nguoi_dung',
            name='thoigianVAO',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
