# Generated by Django 4.0.3 on 2022-11-13 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_alter_log_date_alter_log_time_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='ida',
        ),
        migrations.RemoveField(
            model_name='log',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='log',
            name='status',
        ),
        migrations.RemoveField(
            model_name='nguoi_dung',
            name='thoigianRA',
        ),
        migrations.RemoveField(
            model_name='nguoi_dung',
            name='thoigianVAO',
        ),
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2022, 11, 13, 12, 49, 37, 99887)),
        ),
    ]
