# Generated by Django 4.0.3 on 2022-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_remove_log_date_remove_log_ida_remove_log_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Nguoi_Dung',
        ),
        migrations.AlterField(
            model_name='books',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
