# Generated by Django 4.0.3 on 2022-11-19 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_alter_books_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='releaseDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
