# Generated by Django 4.0.3 on 2022-11-21 12:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_alter_books_releasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ThoiTiet',
        ),
        migrations.AlterField(
            model_name='books',
            name='authorName',
            field=models.CharField(max_length=200, verbose_name='Tên tác giả'),
        ),
        migrations.AlterField(
            model_name='books',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookName',
            field=models.CharField(default=None, max_length=50, verbose_name='Tên cuốn sách'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Lãng mạn', 'Lãng mạn'), ('Trinh thám', 'Trinh thám'), ('Khoa học', 'Khoa học'), ('Nghệ Thuật', 'Nghệ Thuật'), ('Thể Thao', 'Thể Thao')], default=None, max_length=12, verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='books',
            name='decriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Số trang'),
        ),
        migrations.AlterField(
            model_name='books',
            name='releaseDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày phát hành'),
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.books'),
        ),
    ]
