# Generated by Django 4.0.3 on 2022-11-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_cart_delete_thoitiet_alter_books_authorname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.books', verbose_name='Cuốn sách'),
        ),
    ]
