# Generated by Django 4.0.3 on 2022-11-21 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0038_books_price_alter_cart_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người mua'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Giá (USD)'),
        ),
    ]
