# Generated by Django 4.0.3 on 2022-11-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0041_remove_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
