# Generated by Django 4.0.3 on 2022-11-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
