# Generated by Django 4.0.3 on 2022-11-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0051_alter_cartitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer',
        ),
    ]
