# Generated by Django 4.0.3 on 2022-11-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0052_remove_cartitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='product',
            new_name='books',
        ),
    ]
