# Generated by Django 4.0.3 on 2022-11-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0054_productreview_delete_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='books',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5, max_length=150, verbose_name='Số sao'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(verbose_name='Đánh giá'),
        ),
    ]
