# Generated by Django 4.0.3 on 2022-11-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0058_alter_productreview_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myApp.books'),
        ),
    ]
