# Generated by Django 4.0.3 on 2022-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0060_alter_productreview_options_productreview_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
    ]
