# Generated by Django 4.0.3 on 2022-11-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0062_remove_cart_transaction_id_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='user',
        ),
    ]
