# Generated by Django 4.0.3 on 2022-11-26 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0063_rename_customer_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Số trang'),
        ),
    ]
