# Generated by Django 4.0.3 on 2022-12-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0064_alter_books_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
