# Generated by Django 4.0.3 on 2022-12-28 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0067_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myApp.cartitem'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(blank=True, default=100, null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='Số trang'),
        ),
    ]
