# Generated by Django 4.0.3 on 2022-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0072_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='myApp.cartitem'),
        ),
    ]
