# Generated by Django 4.0.3 on 2022-12-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0075_remove_order_cart_items_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
